json.id quilt.id
json.name quilt.name
json.price quilt.price
json.size quilt.size
json.description quilt.description
json.discount quilt.is_discounted
json.tax quilt.tax
json.total quilt.total
json.supplier_id quilt.supplier_id